export enum SceneNames {
  ADD_NEW_BOT_SCENE = "add_new_bot",
  MY_BOTS_SCENE = "my_bots",
  DELETE_BOT_SCENE = "delete_bot_scene",
  BOT_DETAILS_SCENE = "bot_details",
  BOT_GREETINGS_SCENE = "bot_greetings",
  CREATE_GREETING_SCENE = "create_greeting",
  GREETING_DETAILS_SCENE = "greeting_details",
  EDIT_GREETING_DELAY_SCENE = "edit_greeting_delay",
  EDIT_GREETING_PICTURE_SCENE = "edit_greeting_picture",
  ADD_BUTTON_SCENE = "add_button",
  EDIT_GREETING_TEXT_SCENE = "edit_greeting",
  ADMIN_CONTROL_PANEL_SCENE = "admin_control_panel",
  ADMIN_MANAGE_USERS_SCENE = "admin_manage_users",
  ADMIN_ADD_USER_SCENE = "admin_add_user",
  ADMIN_DELETE_USER_SCENE = "admin_delete_user",
  CREATE_FAREWELL_SCENE = "create_farewell",
  BOT_FAREWELLS_SCENE = "farewells",
  FAREWELL_DETAILS_SCENE = "farewell_details",
  EDIT_FAREWELL_TEXT_SCENE = "edit_farewell_text",
  FAREWELL_ADD_BUTTON_SCENE = "farewell_add_button",
  CONNECTED_CHANNELS_SCENE = "connected_channels",
  CHANNEL_DETAILS_SCENE = "channel_details",
  CHANNEL_PUBLISH_POST_SCENE = "channel_publish_post",
  CHANNEL_PUBLISH_POST_SETTINGS_SCENE = "channel_publish_post_settings",
}